name: documentation

on:
  push:
    branches:
      - master
      
env:
  BUILD_DIR: 'source/DocFx/_site'
  DOCFX_FILE: 'source/DocFx/docfx.json'
  GH_PAT: ${{ secrets.DEPLOY_DOCUMENTATION_PERSONAL_ACCESS_TOKEN }}

jobs:
  documentation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build Documentation
      uses: nikeee/docfx-action@master
      with:
        args: ${{ env.DOCFX_FILE }}
    - name: Publish documentation on github pages
      uses: maxheld83/ghpages@master
      env:
        BUILD_DIR: ${{ env.BUILD_DIR }}
        GH_PAT: ${{ env.GH_PAT }}
